DROP TABLE IF EXISTS b_accounts_cmps CASCADE;

CREATE TABLE b_accounts_cmps
(
   pk_account                                varchar(36),
   social_network_name                       varchar(200),
   campain_name                              varchar(200),
   organisation_name                         varchar(45),
   nb_account_viewed                         integer,
   nb_account_viewed_moins_un                integer,
   nb_account_viewed_diff                    integer,
   nb_account_likes                          integer,
   nb_account_likes_moins_un                 integer,
   nb_account_likes_diff                     integer,
   nb_account_follows                        integer,
   nb_account_follows_moins_un               integer,
   nb_account_follows_diff                   integer,
   nb_account_followed                       integer,
   nb_account_followed_moins_un              integer,
   nb_account_followed_diff                  integer,
   nb_account_talking_about                  integer,
   nb_account_talking_about_moins_un         integer,
   nb_account_talking_about_diff             integer,
   nb_account_comment                        integer,
   nb_account_comment_moins_un               integer,
   nb_account_comment_diff                   integer,
   nb_post_viewed                            integer,
   nb_post_viewed_moins_un                   integer,
   nb_post_viewed_diff                       integer,
   nb_post_liked                             integer,
   nb_post_liked_moins_un                    integer,
   nb_post_liked_diff                        integer,
   nb_post_disliked                          integer,
   nb_post_disliked_moins_un                 integer,
   nb_post_disliked_diff                     integer,
   nb_post_shared                            integer,
   nb_post_shared_moins_un                   integer,
   nb_post_shared_diff                       integer,
   nb_post_comment                           integer,
   nb_post_comment_moins_un                  integer,
   nb_post_comment_diff                      integer,
   nb_post                                   integer,
   nb_post_moins_un                          integer,
   nb_post_diff                              integer,
   nb_employee                               integer,
   nb_employee_moins_un                      integer,
   nb_employee_diff                          integer,
   observation_date                          date,
   observation_date_moins_un                 date,
   nb_post_viewed_moyen                      float8,
   nb_post_viewed_moyen_moins_un             float8,
   nb_post_viewed_moyen_diff                 float8,
   nb_post_liked_moyen                       float8,
   nb_post_liked_moyen_moins_un              float8,
   nb_post_liked_moyen_diff                  float8,
   nb_post_liked_by_viewed                   float8,
   nb_post_liked_by_viewed_moins_un          float8,
   nb_post_liked_by_viewed_diff              float8,
   nb_post_liked_moyen_by_follower           float8,
   nb_post_liked_moyen_by_follower_moins_un  float8,
   nb_post_liked_moyen_by_follower_diff      float8,
   nb_jour                                   integer,
   nb_jour_moins_un                          integer,
   niveau                                    varchar(30),
   niveau_moins_un                           varchar(30),
   description                               varchar(30),
   description_moins_un                      varchar(30)
);

GRANT SELECT, RULE, INSERT, TRIGGER, DELETE, REFERENCES, UPDATE ON b_accounts_cmps TO elipce_rs;

COMMIT;
